{"name":"20_Silver_Host","ppdf:dataflowId":"b2e86079-d91c-48a2-a705-fd7da512a545","ppdf:owner":{"tenantId":"ae6c8cb4-6ba6-4c28-b44a-425ca91ff4d5","userId":"f6b3fe48-d23d-4612-adff-5d62f6281d47"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2024-03-17T18:06:43.6458372+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"listings_details":{"queryId":"e4961146-68e8-4283-8a68-f63cf99cf6e5","queryName":"listings_details","queryGroupId":"10dcb8e3-7f98-4836-b1a4-f1cc5ea8e0ca","loadEnabled":true},"Host":{"queryId":"c3adcf66-4a64-489f-a8a2-1a7d83a9d4b3","queryName":"Host","queryGroupId":"f8872f67-889d-46ef-b823-f45f2d102b1d","loadEnabled":true},"Host_DataDestination":{"queryId":"64006cd4-c9f5-4879-8f60-769153d53e1f","queryName":"Host_DataDestination"},"Host_WriteToDataDestination":{"queryId":"c1d5c343-a4d8-4cc2-b72a-c3fea2c2cac6","queryName":"Host_WriteToDataDestination"},"Host_TransformForWriteToDataDestination":{"queryId":"079af746-a7f7-499d-a883-3cfa894dc0bc","queryName":"Host_TransformForWriteToDataDestination"}},"document":"section Section1;\r\nshared listings_details = let\n  Source = Lakehouse.Contents(null){[workspaceId = \"b83630b1-32bc-4102-87f0-ec38a52ae51a\"]}[Data]{[lakehouseId = \"11d90541-29d0-47d6-ac9b-3b44fa2f2281\"]}[Data],\n  listings_details = Source{[Id = \"listings_details\", ItemKind = \"Table\"]}[Data],\n  ChangeColumnTypes = Table.TransformColumnTypes(listings_details, {{\"id\", Int64.Type}, {\"scrape_id\", Int64.Type}, {\"last_scraped\", type date}, {\"host_id\", Int64.Type}, {\"host_since\", type date}, {\"host_listings_count\", Int64.Type}, {\"host_total_listings_count\", Int64.Type}, {\"latitude\", type number}, {\"longitude\", type number}, {\"accommodates\", Int64.Type}, {\"bathrooms\", Int64.Type}, {\"beds\", Int64.Type}, {\"price\", Currency.Type}, {\"minimum_nights\", Int64.Type}, {\"maximum_nights\", Int64.Type}, {\"minimum_minimum_nights\", Int64.Type}, {\"maximum_minimum_nights\", Int64.Type}, {\"minimum_maximum_nights\", Int64.Type}, {\"maximum_maximum_nights\", Int64.Type}, {\"minimum_nights_avg_ntm\", type number}, {\"maximum_nights_avg_ntm\", type number}, {\"availability_30\", Int64.Type}, {\"availability_60\", Int64.Type}, {\"availability_90\", Int64.Type}, {\"availability_365\", Int64.Type}, {\"number_of_reviews\", Int64.Type}, {\"number_of_reviews_ltm\", Int64.Type}, {\"number_of_reviews_l30d\", Int64.Type}, {\"calculated_host_listings_count\", Int64.Type}, {\"calculated_host_listings_count_entire_homes\", Int64.Type}, {\"calculated_host_listings_count_private_rooms\", Int64.Type}, {\"calculated_host_listings_count_shared_rooms\", Int64.Type}, {\"calendar_last_scraped\", type date}, {\"first_review\", type date}, {\"last_review\", type date}, {\"review_scores_rating\", type number}, {\"review_scores_accuracy\", type number}, {\"review_scores_cleanliness\", type number}, {\"review_scores_checkin\", type number}, {\"review_scores_communication\", type number}, {\"review_scores_location\", type number}, {\"review_scores_value\", type number}, {\"reviews_per_month\", type number}})\nin\n  ChangeColumnTypes;\r\n[Staging = \"DefaultStaging\"]\r\nshared Host = let\n  Source = listings_details,\n  RemoveOtherColumns = Table.SelectColumns(listings_details, {\"host_id\", \"host_url\", \"host_name\", \"host_since\", \"host_location\", \"host_about\", \"host_response_time\", \"host_response_rate\", \"host_acceptance_rate\", \"host_is_superhost\", \"host_thumbnail_url\", \"host_picture_url\", \"host_neighbourhood\"}),\n  SplitLocation = Table.SplitColumn(RemoveOtherColumns, \"host_location\", Splitter.SplitTextByDelimiter(\", \"), {\"host_city\", \"host_country\"}),\n  ReplaceNullResponseTime = Table.ReplaceValue(SplitLocation, \"N/A\", null, Replacer.ReplaceValue, {\"host_response_time\"}),\n  CapitalizeResponseTime = Table.TransformColumns(ReplaceNullResponseTime, {{\"host_response_time\", each Text.Proper(_), type nullable text}}),\n  ReplaceNullResponseRate = Table.ReplaceValue( CapitalizeResponseTime, \"N/A\", null, Replacer.ReplaceValue, {\"host_response_rate\"}),\n  ReplacePercentageResponseRate = Table.ReplaceValue(ReplaceNullResponseRate, \"%\", \"\", Replacer.ReplaceText, {\"host_response_rate\"}),\n  ChangeResponseRatePercentage = Table.TransformColumnTypes(ReplacePercentageResponseRate, {{\"host_response_rate\", Percentage.Type}}),\n  DivideResponseRateBy100 = Table.TransformColumns(ChangeResponseRatePercentage, {{\"host_response_rate\", each _ / 100, Percentage.Type}}),\n  ReplaceNullAcceptanceRate = Table.ReplaceValue(DivideResponseRateBy100, \"N/A\", null, Replacer.ReplaceValue, {\"host_acceptance_rate\"}),\n  ReplacePercentageAcceptanceRate = Table.ReplaceValue(ReplaceNullAcceptanceRate, \"%\", \"\", Replacer.ReplaceText, {\"host_acceptance_rate\"}),\n  ChangeAcceptanceRatePercentage = Table.TransformColumnTypes(ReplacePercentageAcceptanceRate, {{\"host_acceptance_rate\", Percentage.Type}}),\n  DivideAcceptanceRateBy100 = Table.TransformColumns(ChangeAcceptanceRatePercentage, {{\"host_acceptance_rate\", each _ / 100, Percentage.Type}}),\n  ReplaceSuperhost = Table.ReplaceValue(DivideAcceptanceRateBy100, \"t\", \"Superhost\", Replacer.ReplaceText, {\"host_is_superhost\"}),\n  ReplaceHost = Table.ReplaceValue(ReplaceSuperhost, \"f\", \"Host\", Replacer.ReplaceText, {\"host_is_superhost\"}),\n  ChangeColumnType = Table.TransformColumnTypes(ReplaceHost, {{\"host_id\", Int64.Type}, {\"host_city\", type text}, {\"host_country\", type text}, {\"host_since\", type date}}),\n  RemoveDuplicates = Table.Distinct(ChangeColumnType),\n  ReorderColumns = Table.ReorderColumns(RemoveDuplicates, {\"host_id\", \"host_name\", \"host_is_superhost\", \"host_since\", \"host_neighbourhood\", \"host_city\", \"host_country\", \"host_response_time\", \"host_response_rate\", \"host_acceptance_rate\", \"host_url\", \"host_picture_url\", \"host_thumbnail_url\", \"host_about\"}),\n  #\"Renamed columns\" = Table.RenameColumns(ReorderColumns, {{\"host_id\", \"Id\"}, {\"host_name\", \"Name\"}, {\"host_is_superhost\", \"HostType\"}, {\"host_since\", \"HostSince\"}, {\"host_neighbourhood\", \"Neighbourhood\"}, {\"host_city\", \"City\"}, {\"host_country\", \"Country\"}, {\"host_response_time\", \"ResponseTime\"}, {\"host_response_rate\", \"ResponseRate\"}, {\"host_acceptance_rate\", \"AcceptanceRate\"}, {\"host_url\", \"HostURL\"}, {\"host_picture_url\", \"HostPictureURL\"}, {\"host_thumbnail_url\", \"HostPictureThumbnailURL\"}, {\"host_about\", \"About\"}})\nin\n  #\"Renamed columns\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared Host_DataDestination = let\r\n  Pattern = Lakehouse.Contents([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"b83630b1-32bc-4102-87f0-ec38a52ae51a\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"b2d0721e-13cb-45db-997e-7b7b39deab08\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"Host\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[Id = nullable Int64.Type, Name = nullable Text.Type, HostType = nullable Text.Type, HostSince = nullable Date.Type, Neighbourhood = nullable Text.Type, City = nullable Text.Type, Country = nullable Text.Type, ResponseTime = nullable Text.Type, ResponseRate = nullable Percentage.Type, AcceptanceRate = nullable Percentage.Type, HostURL = nullable Text.Type, HostPictureURL = nullable Text.Type, HostPictureThumbnailURL = nullable Text.Type, About = nullable Text.Type], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared Host_WriteToDataDestination = let\r\n  Host_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = Host_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], Host_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  Host_WriteToDataDestination;\r\nshared Host_TransformForWriteToDataDestination = let\r\n    SourceTable = Table.SelectColumns(Host, {\"Id\", \"Name\", \"HostType\", \"HostSince\", \"Neighbourhood\", \"City\", \"Country\", \"ResponseTime\", \"ResponseRate\", \"AcceptanceRate\", \"HostURL\", \"HostPictureURL\", \"HostPictureThumbnailURL\", \"About\"})\r\nin\r\n    SourceTable;\r\n","connectionOverrides":[{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"Id\":\"10dcb8e3-7f98-4836-b1a4-f1cc5ea8e0ca\",\"Name\":\"Bronze\",\"Description\":\"\",\"ParentId\":null,\"Order\":0},{\"Id\":\"f8872f67-889d-46ef-b823-f45f2d102b1d\",\"Name\":\"Silver\",\"Description\":\"\",\"ParentId\":null,\"Order\":1}]"}],"entities":[{"$type":"LocalEntity","name":"listings_details","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"listings_details.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"id","dataType":"int64"},{"name":"listing_url","dataType":"string"},{"name":"scrape_id","dataType":"int64"},{"name":"last_scraped","dataType":"date"},{"name":"source","dataType":"string"},{"name":"name","dataType":"string"},{"name":"description","dataType":"string"},{"name":"neighborhood_overview","dataType":"string"},{"name":"picture_url","dataType":"string"},{"name":"host_id","dataType":"int64"},{"name":"host_url","dataType":"string"},{"name":"host_name","dataType":"string"},{"name":"host_since","dataType":"date"},{"name":"host_location","dataType":"string"},{"name":"host_about","dataType":"string"},{"name":"host_response_time","dataType":"string"},{"name":"host_response_rate","dataType":"string"},{"name":"host_acceptance_rate","dataType":"string"},{"name":"host_is_superhost","dataType":"string"},{"name":"host_thumbnail_url","dataType":"string"},{"name":"host_picture_url","dataType":"string"},{"name":"host_neighbourhood","dataType":"string"},{"name":"host_listings_count","dataType":"int64"},{"name":"host_total_listings_count","dataType":"int64"},{"name":"host_verifications","dataType":"string"},{"name":"host_has_profile_pic","dataType":"string"},{"name":"host_identity_verified","dataType":"string"},{"name":"neighbourhood","dataType":"string"},{"name":"neighbourhood_cleansed","dataType":"string"},{"name":"neighbourhood_group_cleansed","dataType":"string"},{"name":"latitude","dataType":"double"},{"name":"longitude","dataType":"double"},{"name":"property_type","dataType":"string"},{"name":"room_type","dataType":"string"},{"name":"accommodates","dataType":"int64"},{"name":"bathrooms","dataType":"int64"},{"name":"bathrooms_text","dataType":"string"},{"name":"bedrooms","dataType":"string"},{"name":"beds","dataType":"int64"},{"name":"amenities","dataType":"string"},{"name":"price","dataType":"decimal"},{"name":"minimum_nights","dataType":"int64"},{"name":"maximum_nights","dataType":"int64"},{"name":"minimum_minimum_nights","dataType":"int64"},{"name":"maximum_minimum_nights","dataType":"int64"},{"name":"minimum_maximum_nights","dataType":"int64"},{"name":"maximum_maximum_nights","dataType":"int64"},{"name":"minimum_nights_avg_ntm","dataType":"double"},{"name":"maximum_nights_avg_ntm","dataType":"double"},{"name":"calendar_updated","dataType":"string"},{"name":"has_availability","dataType":"string"},{"name":"availability_30","dataType":"int64"},{"name":"availability_60","dataType":"int64"},{"name":"availability_90","dataType":"int64"},{"name":"availability_365","dataType":"int64"},{"name":"calendar_last_scraped","dataType":"date"},{"name":"number_of_reviews","dataType":"int64"},{"name":"number_of_reviews_ltm","dataType":"int64"},{"name":"number_of_reviews_l30d","dataType":"int64"},{"name":"first_review","dataType":"date"},{"name":"last_review","dataType":"date"},{"name":"review_scores_rating","dataType":"double"},{"name":"review_scores_accuracy","dataType":"double"},{"name":"review_scores_cleanliness","dataType":"double"},{"name":"review_scores_checkin","dataType":"double"},{"name":"review_scores_communication","dataType":"double"},{"name":"review_scores_location","dataType":"double"},{"name":"review_scores_value","dataType":"double"},{"name":"license","dataType":"string"},{"name":"instant_bookable","dataType":"string"},{"name":"calculated_host_listings_count","dataType":"int64"},{"name":"calculated_host_listings_count_entire_homes","dataType":"int64"},{"name":"calculated_host_listings_count_private_rooms","dataType":"int64"},{"name":"calculated_host_listings_count_shared_rooms","dataType":"int64"},{"name":"reviews_per_month","dataType":"double"}]},{"$type":"LocalEntity","name":"Host","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Host.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[{\"columns\":[\"Id\",\"HostURL\",\"Name\",\"HostSince\",\"City\",\"Country\",\"About\",\"ResponseTime\",\"ResponseRate\",\"AcceptanceRate\",\"HostType\",\"HostPictureThumbnailURL\",\"HostPictureURL\",\"Neighbourhood\"]}]"}],"attributes":[{"name":"Id","dataType":"int64"},{"name":"Name","dataType":"string"},{"name":"HostType","dataType":"string"},{"name":"HostSince","dataType":"date"},{"name":"Neighbourhood","dataType":"string"},{"name":"City","dataType":"string"},{"name":"Country","dataType":"string"},{"name":"ResponseTime","dataType":"string"},{"name":"ResponseRate","dataType":"decimal"},{"name":"AcceptanceRate","dataType":"decimal"},{"name":"HostURL","dataType":"string"},{"name":"HostPictureURL","dataType":"string"},{"name":"HostPictureThumbnailURL","dataType":"string"},{"name":"About","dataType":"string"}]}]}