{"name":"99_Setup_Load_Metadata_InsideAirbnb","ppdf:dataflowId":"df9dd702-94c2-4628-9dd4-ccf935452e29","ppdf:owner":{"tenantId":"ae6c8cb4-6ba6-4c28-b44a-425ca91ff4d5","userId":"f6b3fe48-d23d-4612-adff-5d62f6281d47"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2024-03-17T19:21:39.7479017+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Metadata_InsideAirbnb":{"queryId":"7b89f17c-834b-4053-9f2e-8cb2b32015d7","queryName":"Metadata_InsideAirbnb","loadEnabled":true},"Metadata_InsideAirbnb_DataDestination":{"queryId":"fb97c67f-5511-4c16-8a76-aa3583855197","queryName":"Metadata_InsideAirbnb_DataDestination"},"Metadata_InsideAirbnb_WriteToDataDestination":{"queryId":"0a6edf8d-fc75-4cda-b7b6-df5081179d77","queryName":"Metadata_InsideAirbnb_WriteToDataDestination"},"Metadata_InsideAirbnb_TransformForWriteToDataDestination":{"queryId":"8c6b141c-d3e6-43de-a00c-52c90b04e89d","queryName":"Metadata_InsideAirbnb_TransformForWriteToDataDestination"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared Metadata_InsideAirbnb = let\n  Source = Web.BrowserContents(\"http://insideairbnb.com/get-the-data/\"),\n  URL = Html.Table(Source, {{\"URL\", \"a[href^=\"\"http\"\"]\", each [Attributes][href]}}),\n  DataURL = Table.SelectRows(URL, each Text.Contains([URL], \"data.insideairbnb.com/\") and not Text.Contains([URL], \"geojson\")),\n  RelativeURL = Table.AddColumn(DataURL, \"RelativeURL\", each Text.AfterDelimiter([URL], \".com\", 0), type text),\n  SplitURL = Table.AddColumn(RelativeURL, \"SplitURL\", each Text.AfterDelimiter([URL], \"/\", 2), type text),\n  SplitColumnByDelimiter = Table.SplitColumn(SplitURL, \"SplitURL\", Splitter.SplitTextByDelimiter(\"/\"), {\"SplitURLCountry\", \"SplitURLRegion\", \"SplitURLCity\", \"SplitURLDate\", \"SplitURLFolder\", \"SplitURLFile\"}),\n  Country = Table.AddColumn(SplitColumnByDelimiter, \"Country\", each Text.Proper(Replacer.ReplaceText([SplitURLCountry], \"-\", \" \")), type text),\n  Region = Table.AddColumn(Country, \"Region\", each if [SplitURLFile] = null then null else Text.Proper(Replacer.ReplaceText([SplitURLRegion], \"-\", \" \")), type text),\n  City = Table.AddColumn(Region, \"City\", each if [SplitURLFile] = null then null else Text.Proper(Replacer.ReplaceText([SplitURLCity], \"-\", \" \")), type text),\n  Date = Table.AddColumn(City, \"Date\", each if [SplitURLFile] = null then [SplitURLRegion] else [SplitURLDate]),\n  Folder = Table.TransformColumnTypes(Table.AddColumn(Date, \"Folder\", each if [SplitURLFile] = null then [SplitURLCity] else [SplitURLFolder]), {{\"Folder\", type text}}),\n  FileName = Table.AddColumn(Folder, \"FileName\", each if [SplitURLFile] = null then [SplitURLDate] else [SplitURLFile], type text),\n  FileExtension = Table.SplitColumn(Table.TransformColumnTypes(FileName, {{\"FileName\", type text}}), \"FileName\", Splitter.SplitTextByEachDelimiter({\".\"}, QuoteStyle.Csv), {\"FileName\", \"FileExtension\"}),\n  DestinationFolder = Table.AddColumn(FileExtension, \"DestinationFolder\", each if [SplitURLFile] = null then [SplitURLCountry] else Text.Combine({[SplitURLCountry], [SplitURLRegion], [SplitURLCity]}, \"/\"), type text),\n  DestinationFileName = Table.TransformColumnTypes(Table.AddColumn(DestinationFolder, \"DestinationFileName\", each if [Folder] = \"data\" then [FileName]&\"_details\" else [FileName]), {{\"DestinationFileName\", type text}}),\n  System = Table.AddColumn(DestinationFileName, \"System\", each \"InsideAirbnb\"),\n  RemovedColumns = Table.RemoveColumns(System, {\"SplitURLCountry\", \"SplitURLRegion\", \"SplitURLCity\", \"SplitURLDate\", \"SplitURLFolder\", \"SplitURLFile\"}),\n  ChangedColumnType = Table.TransformColumnTypes(RemovedColumns, {{\"URL\", type text}, {\"Date\", type date}, {\"System\", type text}})\nin\n  ChangedColumnType;\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared Metadata_InsideAirbnb_DataDestination = let\r\n  Pattern = Lakehouse.Contents([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"b83630b1-32bc-4102-87f0-ec38a52ae51a\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"11d90541-29d0-47d6-ac9b-3b44fa2f2281\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"metadata_insideairbnb\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[URL = nullable Text.Type, RelativeURL = nullable Text.Type, Country = nullable Text.Type, Region = nullable Text.Type, City = nullable Text.Type, Date = nullable Date.Type, Folder = nullable Text.Type, FileName = nullable Text.Type, FileExtension = nullable Text.Type, DestinationFolder = nullable Text.Type, DestinationFileName = nullable Text.Type, System = nullable Text.Type], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared Metadata_InsideAirbnb_WriteToDataDestination = let\r\n  Metadata_InsideAirbnb_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = Metadata_InsideAirbnb_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], Metadata_InsideAirbnb_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  Metadata_InsideAirbnb_WriteToDataDestination;\r\nshared Metadata_InsideAirbnb_TransformForWriteToDataDestination = let\r\n    SourceTable = Table.SelectColumns(Metadata_InsideAirbnb, {\"URL\", \"RelativeURL\", \"Country\", \"Region\", \"City\", \"Date\", \"Folder\", \"FileName\", \"FileExtension\", \"DestinationFolder\", \"DestinationFileName\", \"System\"})\r\nin\r\n    SourceTable;\r\n","connectionOverrides":[{"path":"https://insideairbnb.com/get-the-data/","kind":"Web","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"95a09762-f792-4f05-aef8-b2d3682e9187","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null},{"path":"http://insideairbnb.com/get-the-data/","kind":"Web","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"3103d9a0-6cf1-473b-8bda-d66c73b335bd","audience":null}]},"entities":[{"$type":"LocalEntity","name":"Metadata_InsideAirbnb","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Metadata_InsideAirbnb.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"URL","dataType":"string"},{"name":"RelativeURL","dataType":"string"},{"name":"Country","dataType":"string"},{"name":"Region","dataType":"string"},{"name":"City","dataType":"string"},{"name":"Date","dataType":"date"},{"name":"Folder","dataType":"string"},{"name":"FileName","dataType":"string"},{"name":"FileExtension","dataType":"string"},{"name":"DestinationFolder","dataType":"string"},{"name":"DestinationFileName","dataType":"string"},{"name":"System","dataType":"string"}]}]}